name: 'Smithy CLI Composite Action'
description: 'GitHub composite action to run a basic build with the Smithy CLI.'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - run: |
        cp -rn ${{ github.action_path }}/bin/ ./
        chmod +x ./gradlew
      shell: bash
    - uses: gradle/wrapper-validation-action@v1
    - run: ./gradlew clean build
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: smithy-output
        path: build/
