name: 'Smithy CLI Composite Action'
description: 'GitHub composite action to run a basic build with the Smithy CLI.'
runs:
  using: 'composite'
  steps:
    - uses: gradle/wrapper-validation-action@v1
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - run: ./gradlew clean build
    - uses: actions/upload-artifact@v3
      with:
        name: smithy-output
        path: build/
