name: 'Smithy CLI Composite Action'
description: 'GitHub composite action to run a basic build with the Smithy CLI.'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - run: cp -rn ${{ github.action_path }}/bin/ ./
      shell: bash
    - uses: gradle/wrapper-validation-action@v1
    - run: |
        chmod +x ./gradlew
        ./gradlew clean build
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: smithy-output
        path: build/smithyprojections/
